---
title: "K Means Example"
author: "Jules Malin"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(factoextra)
library(cluster)
```
## K Means Example
```{r}
data("USArrests") # Loading the data set
df <- scale(USArrests) # Scaling the data
```

```{r}
head(df)
```

```{r}
#using the fviz_nbclust() function to create a plot of the number of clusters aka elbow method
fviz_nbclust(df, kmeans, method = "wss")
```

```{r}
#calculate gap statistic based on number of clusters
#using the clusGap() function (calculates the gap statistic, it's in the cluster package
# to create a plot of the clusters vs. gap statistic
#gap statistic - https://statweb.stanford.edu/~gwalther/gap
#in English, the gap statistic is a metric that helps describe how compact the clusters are

gap_stat <- clusGap(df,
                    FUN = kmeans,
                    nstart = 25,
                    K.max = 10,
                    B = 50)

#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```

```{r}
#perform k-means clustering with k = 4 clusters
km <- kmeans(df, centers = 4, nstart = 25)

#view results
km
```
```{r}
#plot results of final k-means model
fviz_cluster(km, data = df)
```


```{r}
#find means of each cluster
aggregate(USArrests, by=list(cluster=km$cluster), mean)
```

```{r}
#add cluster assigment to original data
final_data <- cbind(USArrests, cluster = km$cluster)

#view final data
head(final_data)
```